export const usersMock = [
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
  {
    firstName: "Juan",
    lastName: "Pérez",
    userId: "juan.perez",
    isBlocked: false,
  },
  {
    firstName: "Luka",
    lastName: "Sielins",
    userId: "luka.sielins",
    isBlocked: true,
  },
]
